name: react-datetime-dayjs scripts

on:
  push:
    branches:
      - main
  pull_request_target:
    types: [assigned, opened, synchronize, reopened]

jobs:
  publish-module:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          ssh-strict: false
      - uses: actions/checkout@v2
        if: ${{ github.event_name == 'pull_request_target' }}
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          ssh-strict: false
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: 'https://npm.pkg.github.com'
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Build and test
        run: |
          npm i --prefer-offline --no-audit
          npm test
          npm run build
      - name: Publish module
        if: ${{ github.event_name == 'push' && github.repository == 'TruckMap/react-datetime-dayjs' }}
        run: |
          npm version major
          git add .
          git commit --amend -m 'publish module [skip ci]' --author="Truckmap[bot] <accounts@truckmap.com>"
          npm publish
          git push --force origin main
          git push --tags
        env:
          GITHUB_TOKEN: ${{ github.token }}
          NODE_AUTH_TOKEN: ${{ github.token }}
          NPM_AUTH_TOKEN: ${{ github.token }}
